services:
  - type: web
    name: financial-advisor-ai
    env: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: financial-advisor-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        value: https://financial-advisor-ai.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: HUBSPOT_CLIENT_ID
        sync: false
      - key: HUBSPOT_CLIENT_SECRET
        sync: false
      - key: HUBSPOT_REDIRECT_URI
        value: https://financial-advisor-ai.onrender.com/api/auth/callback/hubspot
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: financial-advisor-db
    plan: starter
    databaseName: financial_advisor_ai
